### ISSUE TITLE
Incompatible with Conversation View?

### ISSUE THREAD

**Issue by thierrytiti** [Zimbra-Community/list-unsubscribe-zimlet#5]
The button only appear when i choose one message in a conversation.
Initializing with onMsgView appears to be the source on the problem.

**Comment by barrydegraaff** [comment]
Maybe onMsgView needs something like:
   var type = items[0].type;
	var msg;
	if (type == ZmId.ITEM_CONV) {
		msg = items[0].getFirstHotMsg();
	} else if(type == ZmId.ITEM_MSG) {
		msg = items[0];
	}

Can you make an export of you conversation in tgz and mail it to info@barrydegraaff.tk then I will look into it.

**Comment by thierrytiti** [comment]
I think it need to implement .onConvView too.
How i detect the problem:
 - Just move your zimbra mail view in conversation mode 
 - Reload Zimbra
 - select a mail with a List-Unsubscribe header
=> no button appears

**Comment by barrydegraaff** [comment]
onConvView is not a method of zmZimletBase...

**Comment by barrydegraaff** [comment]
The conversation view is not the issue, when a user clicks a message the ZmMailMsg object is passed to the zimlet.

This is the newest message in a conversation, if that message has a list-unsubscribe header, the zimlet works as designed.

If not, no button is showed, because the Zimlet cannot know what unsubscribe action to perform.
